import { z } from 'zod';
import type { RulePolicy } from '../types/types.js';

export const RuleProposalSchema = z.object({
  id: z.string().describe('Kebab-case rule ID (e.g., "no-raw-sql-interpolation")'),
  title: z.string().describe('Short human-readable title'),
  severity: z.enum(['error', 'warning', 'info']),
  globs: z.array(z.string()).describe('File glob patterns this rule applies to'),
  instructions: z.string().describe('What to flag and why — be specific'),
  examples: z
    .object({
      violations: z.array(z.string()).optional().describe('Code snippets (10-120 chars) showing violations'),
      compliant: z.array(z.string()).optional().describe('Code snippets (10-120 chars) showing correct code'),
    })
    .optional()
    .describe('Concrete code examples of violations and compliant patterns'),
  tags: z
    .array(z.string())
    .optional()
    .describe('Lowercase hyphenated tags for categorization (e.g., "architecture", "security")'),
});

export const TriageDecisionSchema = z.object({
  keep: z.array(z.string()).describe('Rule IDs to keep as-is'),
  drop: z.array(z.string()).describe('Rule IDs to remove'),
  merge: z.array(
    z.object({
      target: z.string().describe('ID of the rule to keep as the merged result'),
      sources: z.array(z.string()).describe('IDs of rules being merged into the target'),
      reason: z.string().describe('Brief explanation of why these rules overlap'),
    })
  ),
});

export interface SelectedFile {
  path: string;
  content: string;
  importedByCount: number;
}

export interface ZoneConfig {
  name: string;
  files: string[];
  selectedFiles: SelectedFile[];
  autoGeneratedPaths: string[];
}

export interface ScanResult {
  zones: ZoneConfig[];
  totalSourceFiles: number;
  extensions: Record<string, number>;
  configs: Record<string, string>;
  docs: Record<string, string>;
}

export interface ZoneAnalysisResult {
  zoneName: string;
  rules: RulePolicy[];
  inputTokens: number;
  outputTokens: number;
}

export interface GeneratorResult {
  rules: RulePolicy[];
  summary: {
    filesScanned: number;
    rulesGenerated: number;
    durationMs: number;
    inputTokens: number;
    outputTokens: number;
  };
}

interface GeneratorIndexingEvent {
  type: 'indexing';
}

interface GeneratorScanCompleteEvent {
  type: 'scan_complete';
  totalFiles: number;
  zoneCount: number;
  extensions: Record<string, number>;
}

interface GeneratorZoneStartedEvent {
  type: 'zone_started';
  zoneName: string;
  fileCount: number;
  selectedFileCount: number;
}

interface GeneratorZoneCompletedEvent {
  type: 'zone_completed';
  zoneName: string;
  rulesProposed: number;
  durationMs: number;
}

interface GeneratorSynthesisStartedEvent {
  type: 'synthesis_started';
  candidateCount: number;
}

interface GeneratorSynthesisCompletedEvent {
  type: 'synthesis_completed';
  candidateCount: number;
  finalCount: number;
  durationMs: number;
}

interface GeneratorCompleteEvent {
  type: 'generator_complete';
  totalRules: number;
  durationMs: number;
}

export type GeneratorProgressEvent =
  | GeneratorIndexingEvent
  | GeneratorScanCompleteEvent
  | GeneratorZoneStartedEvent
  | GeneratorZoneCompletedEvent
  | GeneratorSynthesisStartedEvent
  | GeneratorSynthesisCompletedEvent
  | GeneratorCompleteEvent;

export type GeneratorProgressCallback = (event: GeneratorProgressEvent) => void;

export interface GenerateRulesOptions {
  configPath?: string;
  cwd?: string;
  onProgress?: GeneratorProgressCallback;
  abortSignal?: AbortSignal;
}
