import type { RulePolicy } from '../types/types.js';

export interface SelectedFile {
  path: string;
  content: string;
  importedByCount: number;
}

export interface ZoneConfig {
  name: string;
  files: string[];
  selectedFiles: SelectedFile[];
  autoGeneratedPaths: string[];
}

export interface ScanResult {
  zones: ZoneConfig[];
  totalSourceFiles: number;
  extensions: Record<string, number>;
  configs: Record<string, string>;
  docs: Record<string, string>;
}

export interface ZoneAnalysisResult {
  zoneName: string;
  rules: RulePolicy[];
  inputTokens: number;
  outputTokens: number;
}

export interface GeneratorResult {
  rules: RulePolicy[];
  summary: {
    filesScanned: number;
    rulesGenerated: number;
    durationMs: number;
    inputTokens: number;
    outputTokens: number;
  };
}

interface GeneratorIndexingEvent {
  type: 'indexing';
}

interface GeneratorScanCompleteEvent {
  type: 'scan_complete';
  totalFiles: number;
  zoneCount: number;
  extensions: Record<string, number>;
}

interface GeneratorZoneStartedEvent {
  type: 'zone_started';
  zoneName: string;
  fileCount: number;
  selectedFileCount: number;
}

interface GeneratorZoneCompletedEvent {
  type: 'zone_completed';
  zoneName: string;
  rulesProposed: number;
  durationMs: number;
}

interface GeneratorSynthesisStartedEvent {
  type: 'synthesis_started';
  candidateCount: number;
}

interface GeneratorSynthesisCompletedEvent {
  type: 'synthesis_completed';
  candidateCount: number;
  finalCount: number;
  durationMs: number;
}

interface GeneratorCompleteEvent {
  type: 'generator_complete';
  totalRules: number;
  durationMs: number;
}

export type GeneratorProgressEvent =
  | GeneratorIndexingEvent
  | GeneratorScanCompleteEvent
  | GeneratorZoneStartedEvent
  | GeneratorZoneCompletedEvent
  | GeneratorSynthesisStartedEvent
  | GeneratorSynthesisCompletedEvent
  | GeneratorCompleteEvent;

export type GeneratorProgressCallback = (event: GeneratorProgressEvent) => void;

export interface GenerateRulesOptions {
  configPath?: string;
  cwd?: string;
  onProgress?: GeneratorProgressCallback;
  abortSignal?: AbortSignal;
}
